import LayoutProvider from "@/components/LayoutProvider";
import '../app/globals.css'
import "../stylesheets/layout.css";


export const metadata = {
  title: "RecruitYes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
      <LayoutProvider>{children}</LayoutProvider>
    
  );
}